### ISSUE TITLE
Files opening in same tab, changes to settings.json not applied

### ISSUE THREAD

**Issue by joeparislbcc** [nicoespeon/vscode-slides#14]
## Describe the bug

When running VS Code Slides a new `settings.json` file is created but *not* saved and therefore does not get applied. Further, all markdown files are open in the *same* tab.

## How to reproduce

Open a folder containing markdown files and press `ctrl+alt+p` to engage presentation mode.

## Expected behavior

Current editor settings are saved, presentation-friendly settings are applied, and every file in the open folder is opened in its own tab in the editor.

## Screenshots

![screenshot](https://media.giphy.com/media/cLwOphdDZhXEdoWgeB/giphy.gif)

## Additional information

- Windows 10 1903 (build 18362.535)
- VS Code 1.41.1
- Installed extensions:
  - [:emojisense: v0.5.3](https://github.com/mattbierner/vscode-emojisense.git)
  - [autoDocstring v0.4.0](https://github.com/NilsJPWerner/autoDocstring)
  - [change-case v1.0.0](https://github.com/wmaurer/vscode-change-case.git)
  - [Cobalt2 Theme Official v2.1.6](https://github.com/wesbos/cobalt2-vscode)
  - [Code Runner v0.9.15](https://github.com/formulahendry/vscode-code-runner.git)
  - [Code Spell Checker v 1.7.20](https://github.com/streetsidesoftware/vscode-spell-checker)
  - [Docker v0.9.0](https://github.com/microsoft/vscode-docker)
  - [Docker Explorer v0.1.6](https://github.com/formulahendry/vscode-docker-explorer.git)
  - [EditorConfig for VS Code v0.14.4](https://github.com/editorconfig/editorconfig-vscode.git)
  - [Encode Decode v1.3.0](https://github.com/mitchdenny/ecdc.git)
  - [Formatting Toggle v2.0.0](https://github.com/Tom-Bonnike/vscode-formatting-toggle.git)
  - [GitHub Clean White Theme v0.0.3](https://github.com/saviorisdead/vscode-github-clean-white-theme)
  - [GitLens - Git supercharged v10.1.0](https://github.com/eamodio/vscode-gitlens.git)
  - [hexdump for VSCode v1.7.2](https://github.com/stef-levesque/vscode-hexdump.git)
  - [Indenticator v0.6.0](https://github.com/SirTori/indenticator)
  - [LaTeX Workshop v8.5.0](https://github.com/James-Yu/LaTeX-Workshop.git)
  - [Material Icon Theme v3.9.2](https://github.com/PKief/vscode-material-icon-theme.git)
  - [Path Intellisense v1.4.2](https://github.com/ChristianKohler/PathIntellisense.git)
  - [PowerShell v2019.12.0](https://github.com/PowerShell/vscode-powershell.git)
  - [Quick and Simple Text Selection v 0.2.8](https://github.com/dbankier/vscode-quick-select/)
  - [Remote - Containers v0.94.0](https://github.com/Microsoft/vscode-remote-release.git)
  - [Remote - SSH v0.48.0](https://github.com/Microsoft/vscode-remote-release.git)
  - [Remote - SSH:Editing Configuration Files v0.48.0](https://github.com/Microsoft/vscode-remote-release.git)
  - [Remote - SSH: Explorer v0.48.0](https://github.com/Microsoft/vscode-remote-release.git)
  - [Remote - WSL v0.41.6](https://github.com/Microsoft/vscode-remote-release.git)
  - [Remote Development Extension Pack v0.19.0](https://github.com/Microsoft/vscode-remote-release.git)
  - [Settings Sync v3.4.3](https://github.com/shanalikhan/code-settings-sync.git)
  - [VS Code Slides v3.2.0](https://github.com/nicoespeon/vscode-slides.git)
  - [Sublime Commands v0.1.0](https://github.com/Zarel/vscode-sublime-commands.git)
  - [Terminal Here v0.2.4](https://github.com/Tyriar/vscode-terminal-here)
  - [VSCode Hacker Typer v0.1.1](https://github.com/jevakallio/vscode-hacker-typer)
  - [vscode-pandoc v0.0.8](https://github.com/dfinke/vscode-pandoc.git)

**Comment by nicoespeon** [comment]
Oh, good catch @joeparislbcc 👍 

Indeed, it probably worked out of the box for me because I have auto-save enabled globally on my VS Code, so the new `settings.json` is saved after creation. But it should work even without that. The extension should ensure to save the file.

Thanks for reporting, I'll fix that soon 😉

**Comment by nicoespeon** [comment]
@all-contributors please add joeparislbcc for bug
