### ISSUE TITLE
command 'slides.toggle' not found

### ISSUE THREAD

**Issue by kurt-o-sys** [nicoespeon/vscode-slides#16]
I just installed vscode slides plugin.
I added a test.md file.

When I try to start slides, than I get the `command 'slides.toggle' not found` error:

![image](https://user-images.githubusercontent.com/2430465/71975802-24b89500-3215-11ea-9555-ac9a8c76eea0.png)

I basically can't start 'slides' :p.

**Comment by nicoespeon** [comment]
Oh, that's strange. It looks like it wasn't activated, which VS Code usually do when it loads.

If you **Reload VS Code window** and try again, does it work?

![image](https://user-images.githubusercontent.com/1094774/71980541-96e2a700-3220-11ea-9419-82b16e2bb3f6.png)

If not, can you also try quitting and launching VS Code again to see if it works?

**Comment by kurt-o-sys** [comment]
I tried both reloading and quitting/relaunching... Still doesn't work. 

It is installed:

![image](https://user-images.githubusercontent.com/2430465/72048671-964c1e00-32bd-11ea-8197-cd99ce752fa6.png)

**Comment by nicoespeon** [comment]
Oh, that's weird, it looks like there is a problem with the published extension then.

I completely uninstalled my extension and re-installed to check, but it's working correctly.

Thus, can you try:

1. To uninstall the extension
2. To ensure the extension files are deleted (if you're on Mac or Linux, check at `$HOME/.vscode/packages` that you don't have a `nicoespeon.slides` folder anymore)
3. Re-install the extension

Do the problem still persist? 
If so, can you tell me what's your OS and what other extensions you have installed? Maybe there is a conflict or something.

**Comment by nicoespeon** [comment]
Closing the issue because I can't repro. Feel free to re-open it if you still experience this issue despite my previous advices 👍
