### ISSUE TITLE
vscode launch setting never launches

### ISSUE THREAD

**Issue by divinebovine** [nicoespeon/vscode-slides#2]
## Describe the bug

When opening the repository with vscode and trying to launch the exension for debugging, the launch task never launches. This is because the launch task depends on a prelaunch task completing, `npm watch`. Since this task never completes, the extension never runs.

It might be better to document that you need to run the npm watch task before you try launching the extension. 🤷‍♂

**Comment by nicoespeon** [comment]
Thanks for reporting @divinebovine 😃 

I'm not sure how to get proper watch mode with the debugger. But at least, it should work. I changed the prelaunch task to use build instead.

It will require manual relaunch when code changes, but at least it launches!
