### ISSUE TITLE
Allow overriding key bindings

### ISSUE THREAD

**Issue by divinebovine** [nicoespeon/vscode-slides#4]
## Is this request related to a problem? Please describe.

It would be nice if we could customize the key bindings. Currently on windows the plugin overrides the default behavior of ctrl+left and ctrl+right. That is a common binding for moving the cursor by word boundaries. When this plugin is loaded (not even running) it overrides that behavior.

## Describe the solution you'd like

Add key bindings to the settings.

**Comment by nicoespeon** [comment]
@divinebovine in fact, that's something you can already do by default, thanks to VS Code.

If you open **Keyboard Shortcuts** and type `slides` you'll find the default keybindings of the extension and you can change them.

![image](https://user-images.githubusercontent.com/1094774/69199490-177d0500-0b06-11ea-98f2-939e5d8c8d5d.png)

Do you think we need to make that more explicit in the README?

**Comment by divinebovine** [comment]
Heh, I feel dumb. I should know this, but I didn't realize it.

As far as calling it out, it might be helpful for people who don't know that its possible and might cut down on feature requests like this one :-)

**Comment by nicoespeon** [comment]
Yup, I'll add a word about that 😉
