### ISSUE TITLE
Recent VSCode Versions: "command workbench.action.maximizeEditor not found"

### ISSUE THREAD

**Issue by timvahlbrock** [nicoespeon/vscode-slides#60]
## Describe the bug

When toggling slide mode VSCode throws an error:

This command was renamed: https://github.com/microsoft/vscode/issues/197227 . What's especially annoying is that the editor theming is changed, but wouldn't change back when toggling slide mode again.

## How to reproduce

Use one of the latest VSCode Versions (e.g. latest, 1.85.1)

## Expected behavior

Slide modes starts.

## Screenshots

![image](https://github.com/nicoespeon/vscode-slides/assets/25803754/e69db0c7-c507-43aa-bce7-b994515df096)

## Additional information

- Version of the extension impacted: _v4.2.0

_👩‍🏫 Add any other context about the problem here._

**Comment by nicoespeon** [comment]
Great catch @timvahlbrock, thanks for pointing out!

I did 2 things:
1. Fixed the command used to be compatible with the latest versions of VS Code
2. Make sure you can toggle settings back if it happens to fail again for any reason

**Comment by nicoespeon** [comment]
@all-contributors please add timvahlbrock for bug

**Comment by timvahlbrock** [comment]
Great, thanks for the quick fix
