### ISSUE TITLE
Ctrl + RightArrow doesn't work to skip to end of word

### ISSUE THREAD

**Issue by gonz4lex** [nicoespeon/vscode-slides#7]
## Describe the bug

The extension is great, however I have found that I can use the Control and arrow keys to move to the end or beginning of a word as per the `cursorWordEndRight` and `cursorWordEndRight` commands. I have experienced this issue in both Markdown and Python files after installing the extension. Also, after disabling it and reloading Code, it appears to work again. Re-enabling the extensions causes it to fail again.

## How to reproduce

I'm afraid I do not have concrete steps for reproducing since this happens by just enabling the extension. I am also NOT in Slides mode when trying this.

## Expected behavior

The cursor should be able to skip words correctly when not in Slides mode.

## Additional information

- Version of the extension impacted: _v2.0.3_

Thank you very much for your time and this extension.

**Comment by nicoespeon** [comment]
@gonz4lex Are you using Windows? Linux?

I think I configured the default keybinding of slides navigation to the same keybinding than `cursorWordEndRight`. 

Hopefully you can change slides defaults in **Preferences > Keyboard Shortcuts**. Look for `slides` and change the keybinding.

![image](https://user-images.githubusercontent.com/1094774/69375690-ea039900-0c76-11ea-8f68-5d3d2cdb7336.png)

I'm keeping the issue open to remind me to change the default keybinding to something that is not already taken 👍

**Comment by nicoespeon** [comment]
ping @fabien0102 if you can help me find the best keybindings for Windows, that would be awesome 🙏

**Comment by gonz4lex** [comment]
@nicoespeon I'm on Windows, yes! Sorry for no detailing that before, not quite used to the process of opening issues yet. :)

I tried to remap the bindings to see if that would override the effect but it didn't work, so for now I will use a custom binding and keep watch for any updates to the defaults.

Thank you very much for your reply and your time!

**Comment by fabien0102** [comment]
We don't really have a lot on choices on windows sadly, I guess we can give a try with `ctrl+shift+alt+arrow`

**Comment by nicoespeon** [comment]
> Sorry for no detailing that before, not quite used to the process of opening issues yet. :)

Oh don't be sorry, you provided enough information! I suspected it was OS-specific because of what you described, just wanted to confirm 😉 

Thanks, I changed the keybinding. I'll release a new version so it will fix the problem @gonz4lex 👍
