### ISSUE TITLE
Ability to Customize Slides Folder

### ISSUE THREAD

**Issue by etbrow** [nicoespeon/vscode-slides#9]
## Feature Description
I try to keep my content that I work with separate so it's easier to maneuver when looking at the repository. I'll have separate folders for each example and sometimes for ad-hoc scripts that we do during the presentation. Being able to specify a specific folder where the slides are located would be a big plus.

**Comment by joeparislbcc** [comment]
I too would find this very useful. I want to use Slides in the classes I teach. I keep a repo per class and under it have folders for each lecture. As it stands, I will either need to copy each folder out of my repo to a new location on disk and open that folder to present from or open a subfolder in my local repo to do the presentation from. Both seem less than optimal. Being able to specify the folder to open files from would be great.

**Comment by etbrow** [comment]
Would you rather it be a configurable global option or prompted at activation? I was thinking just a global setting.

**Comment by joeparislbcc** [comment]
Good question, @etbrow. 🤔 

A global setting would be good, I think. I wouldn't mind setting it before running slides and I suspect that would be the least friction for most people. Personally, having a dialog prompt me for the folder to base on would be just as good but I expect that would be too much of a change from the original behavior that people currently using it would find it offputting.

**Comment by nicoespeon** [comment]
Agree with the proposed feature, that's something I thought about last time I used the extension.

I too think that the best UX would be to provide that customisation through standard VS Code settings. Default will be current behaviour (= workspace root folder). If path to defined folder can't be found, it will show a useful (explicit) error message and won't proceed.

Sounds like a plan 😃

**Comment by etbrow** [comment]
I've got a branch for it going in my fork. I'll work on it for the next few days.

**Comment by joeparislbcc** [comment]
This sounds great to me. Thanks!

Joe Paris
Faculty, Computer Science Department
Linn-Benton Community College

**Comment by etbrow** [comment]
@nicoespeon I believe I have this feature finished. Would you like a separate pull request for it or just merge it into my currently open one?

**Comment by nicoespeon** [comment]
@etbrow if it doesn't conflict, I'd prefer a distinct PR so we can discuss/integrate them separately. If it's based on the previous branch, then I'm fine you push the code in the existing PR and I'll review all of that 😉 

Thanks for taking the time to do this 👍

**Comment by etbrow** [comment]
I'll just do a distinct one to keep things tidy :)

And absolutely. This is my first public contribution so I'm excited to work on it.

**Comment by nicoespeon** [comment]
@all-contributors please add etbrow for ideas and code

**Comment by nicoespeon** [comment]
@all-contributors please add etbrow for code

**Comment by nicoespeon** [comment]
All good. Thank you @etbrow for suggesting this and helping setting up everything 👏 

I'll release this and the preview of Markdown files in a new version right away 😃
